# Generated by Django 4.2.1 on 2023-06-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_portfolio_job1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg', models.CharField(max_length=250)),
                ('college', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
    ]
