# Generated by Django 4.2.1 on 2023-06-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='job2',
            field=models.CharField(default='fullstack developer intern', max_length=250),
            preserve_default=False,
        ),
    ]
