# Generated by Django 4.2.1 on 2023-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_portfolio_job2'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company',
            field=models.CharField(default='inmakes infotech', max_length=250),
            preserve_default=False,
        ),
    ]
