# Generated by Django 4.2.1 on 2023-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_portfolio_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='jobdesc',
            field=models.TextField(default='2020'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='year1',
            field=models.CharField(default='good', max_length=250),
            preserve_default=False,
        ),
    ]
