# Generated by Django 4.2.1 on 2023-06-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
