# Generated by Django 4.2.1 on 2023-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=250)),
                ('skill2', models.CharField(max_length=250)),
                ('skill3', models.CharField(max_length=250)),
                ('skill4', models.CharField(max_length=250)),
                ('skill5', models.CharField(max_length=250)),
                ('skill6', models.CharField(max_length=250)),
            ],
        ),
    ]
