# Generated by Django 4.2.1 on 2023-06-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill5',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill6',
        ),
    ]
