# Generated by Django 4.2.1 on 2023-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_remove_skill_skill2_remove_skill_skill3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
